platform :ios, '8.0'

	target:"RabbitMQDemo" do
    
	use_frameworks!
    
	pod 'RMQClient', '~> 0.10.0'

	pod "Masonry"
	pod "MJExtension"

	pod “JSONModel”

	pod 'Colours','~>5.13.0'
    
	pod 'AFNetworking'
    
end
